@echo off
echo Starting Shunbao Trading Platform...
echo Opening Browser...
start http://localhost:8000
echo Starting Backend Server...
.venv\Scripts\python.exe -m uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
pause
